---
# Source: enterprise-logs/templates/gateway/service-gateway.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-enterprise-logs-gateway
  labels:
  annotations:
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 3100
      protocol: TCP
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: enterprise-logs
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: gateway
    target: gateway
