---
# Source: enterprise-logs/charts/minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-minio
  labels:
    app: minio
    chart: minio-8.0.9
    release: release-name
    heritage: Helm
type: Opaque
data:
  accesskey: "ZW50ZXJwcmlzZS1sb2dz"
  secretkey: "c3VwZXJzZWNyZXQ="
