---
# Source: enterprise-logs/charts/loki-distributed/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-enterprise-logs
  labels:
    helm.sh/chart: loki-distributed-0.55.0
    app.kubernetes.io/name: enterprise-logs
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.6.1"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-enterprise-logs
subjects:
  - kind: ServiceAccount
    name: release-name-enterprise-logs
    namespace: default
