---
# Source: enterprise-logs/charts/loki-distributed/templates/querier/service-querier.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-enterprise-logs-querier
  labels:
    helm.sh/chart: loki-distributed-0.55.0
    app.kubernetes.io/name: enterprise-logs
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.6.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: querier
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
  selector:
    app.kubernetes.io/name: enterprise-logs
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: querier
