---
# Source: enterprise-logs/templates/secret-license.yaml
apiVersion: v1
kind: Secret
metadata:
  name: enterprise-logs-license
  labels:
    helm.sh/chart: enterprise-logs-2.4.2
    app.kubernetes.io/name: enterprise-logs
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.5.2"
    app.kubernetes.io/managed-by: Helm
data:
  license.jwt: Tk9UQVZBTElETElDRU5TRQ==
