---
# Source: enterprise-logs/templates/tokengen/rolebinding-tokengen.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-enterprise-logs-tokengen
  labels:
    helm.sh/chart: enterprise-logs-2.4.2
    app.kubernetes.io/name: enterprise-logs
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.5.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: tokengen
  annotations:
    "helm.sh/hook": post-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-enterprise-logs-tokengen
subjects:
  - kind: ServiceAccount
    name: release-name-enterprise-logs
