---
# Source: enterprise-logs/templates/compactor/statefulset-compactor.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-enterprise-logs-compactor
  labels:
    helm.sh/chart: enterprise-logs-2.4.2
    app.kubernetes.io/name: enterprise-logs
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.5.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: memberlist
  annotations:
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: enterprise-logs
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/component: compactor
      target: compactor
  updateStrategy:
    type: RollingUpdate
  serviceName: release-name-enterprise-logs-compactor
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
          
          - ReadWriteOnce
        resources:
          requests:
            storage: "2Gi"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: enterprise-logs
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/component: compactor
        target: compactor
        app.kubernetes.io/part-of: memberlist
      annotations:
        checksum/config: 74259670e52e4282a017bc33721d2322bc9eb5959309cf2468d3348bff05184d
    spec:
      serviceAccountName: release-name-enterprise-logs
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      initContainers:
        []
      nodeSelector:
        {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: target
                  operator: In
                  values:
                  - compactor
              topologyKey: kubernetes.io/hostname
            weight: 100
      tolerations:
        []
      terminationGracePeriodSeconds: 300
      volumes:
        - name: config
          secret:
            secretName: enterprise-logs-config
        - name: license
          secret:
            secretName: enterprise-logs-license
        - name: storage
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      containers:
        - name: compactor
          image: "docker.io/grafana/enterprise-logs:v1.5.2"
          imagePullPolicy: IfNotPresent
          args:
            - -target=compactor
            - -config.file=/etc/loki/config/config.yaml
            - -admin.client.backend-type=s3
            - -admin.client.s3.endpoint=release-name-minio.default.svc:9000
            - -admin.client.s3.bucket-name=enterprise-logs-admin
            - -admin.client.s3.access-key-id=enterprise-logs
            - -admin.client.s3.secret-access-key=supersecret
            - -admin.client.s3.insecure=true
          volumeMounts:
            - name: config
              mountPath: /etc/loki/config
            - name: license
              mountPath: /etc/enterprise-logs/license
            - name: storage
              mountPath: /var/loki
            - name: tmp
              mountPath: /tmp
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: http-memberlist
              containerPort: 7946
              protocol: TCP
          livenessProbe:
            failureThreshold: 20
            httpGet:
              path: /ready
              port: http-metrics
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 60
          resources:
            {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          env:
