---
# Source: enterprise-logs/charts/loki-distributed/templates/ruler/service-ruler.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-enterprise-logs-ruler
  labels:
    app.kubernetes.io/name: enterprise-logs
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: ruler
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
  selector:
    app.kubernetes.io/name: enterprise-logs
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: ruler
